namespace KrasCore.AccumulatorGenerator
{
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Text;
    using Microsoft.CodeAnalysis;

    [Generator]
    public sealed class AccumulatorGenerator : IIncrementalGenerator
    {
        private const string ATTRIBUTE_METADATA_NAME = "KrasCore.GenerateAccumulatorForAttribute";

        private static readonly SymbolDisplayFormat FullyQualifiedFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var accumulators = context.CompilationProvider
                .Select((compilation, _) => GetAccumulators(compilation));

            context.RegisterSourceOutput(accumulators, (sourceProductionContext, accumulatorData) =>
            {
                foreach (var accumulator in accumulatorData)
                {
                    sourceProductionContext.AddSource($"{accumulator.StructName}.g.cs", GenerateSource(accumulator));
                }
            });
        }

        private static ImmutableArray<AccumulatorData> GetAccumulators(Compilation compilation)
        {
            var attributes = compilation.Assembly.GetAttributes();
            var accumulators = ImmutableArray.CreateBuilder<AccumulatorData>();
            var emittedStructs = new HashSet<string>();

            foreach (var attribute in attributes)
            {
                if (attribute.AttributeClass?.ToDisplayString() != ATTRIBUTE_METADATA_NAME)
                {
                    continue;
                }

                if (attribute.ConstructorArguments.Length != 1 ||
                    attribute.ConstructorArguments[0].Value is not ITypeSymbol typeSymbol)
                {
                    continue;
                }

                var structName = $"Native{GetFriendlyTypeName(typeSymbol)}Accumulator";
                if (!emittedStructs.Add(structName))
                {
                    continue;
                }

                accumulators.Add(new AccumulatorData(
                    GetTypeName(typeSymbol),
                    typeSymbol.ToDisplayString(FullyQualifiedFormat),
                    structName,
                    GetDivisor(typeSymbol)));
            }

            return accumulators.ToImmutable();
        }

        private static string GenerateSource(AccumulatorData accumulator)
        {
            var source = new StringBuilder();
            var addExpression = GetReturnExpression(accumulator, "total + value");
            var divideExpression = GetReturnExpression(accumulator, $"total / {accumulator.Divisor}");

            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            source.AppendLine();
            source.AppendLine($"public struct {accumulator.StructName} : global::KrasCore.INativeAccumulator<{accumulator.FullTypeName}>");
            source.AppendLine("{");
            source.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            source.AppendLine($"    public {accumulator.FullTypeName} Add(in {accumulator.FullTypeName} total, in {accumulator.FullTypeName} value)");
            source.AppendLine("    {");
            source.AppendLine($"        return {addExpression};");
            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            source.AppendLine($"    public {accumulator.FullTypeName} Divide(in {accumulator.FullTypeName} total, int count)");
            source.AppendLine("    {");
            source.AppendLine($"        return {divideExpression};");
            source.AppendLine("    }");
            source.AppendLine("}");

            return source.ToString();
        }

        private static string GetReturnExpression(AccumulatorData accumulator, string expression)
        {
            switch (accumulator.TypeName)
            {
                case "byte":
                case "sbyte":
                case "short":
                case "ushort":
                    return $"({accumulator.FullTypeName})({expression})";
                default:
                    return expression;
            }
        }

        private static string GetDivisor(ITypeSymbol typeSymbol)
        {
            switch (typeSymbol.SpecialType)
            {
                case SpecialType.System_UInt32:
                    return "(uint)count";
                case SpecialType.System_UInt64:
                    return "(ulong)count";
            }

            if (typeSymbol.ContainingNamespace?.ToDisplayString() == "Unity.Mathematics" &&
                (typeSymbol.Name == "uint2" || typeSymbol.Name == "uint3" || typeSymbol.Name == "uint4"))
            {
                return "(uint)count";
            }

            return "count";
        }

        private static string GetTypeName(ITypeSymbol typeSymbol)
        {
            switch (typeSymbol.SpecialType)
            {
                case SpecialType.System_SByte:
                    return "sbyte";
                case SpecialType.System_Byte:
                    return "byte";
                case SpecialType.System_Int16:
                    return "short";
                case SpecialType.System_UInt16:
                    return "ushort";
                case SpecialType.System_Int32:
                    return "int";
                case SpecialType.System_UInt32:
                    return "uint";
                case SpecialType.System_Int64:
                    return "long";
                case SpecialType.System_UInt64:
                    return "ulong";
                case SpecialType.System_Single:
                    return "float";
                case SpecialType.System_Double:
                    return "double";
                default:
                    return typeSymbol.Name;
            }
        }

        private static string GetFriendlyTypeName(ITypeSymbol typeSymbol)
        {
            switch (typeSymbol.SpecialType)
            {
                case SpecialType.System_SByte:
                    return "SByte";
                case SpecialType.System_Byte:
                    return "Byte";
                case SpecialType.System_Int16:
                    return "Short";
                case SpecialType.System_UInt16:
                    return "UShort";
                case SpecialType.System_Int32:
                    return "Int";
                case SpecialType.System_UInt32:
                    return "UInt";
                case SpecialType.System_Int64:
                    return "Long";
                case SpecialType.System_UInt64:
                    return "ULong";
                case SpecialType.System_Single:
                    return "Float";
                case SpecialType.System_Double:
                    return "Double";
                default:
                    return ToPascalCase(typeSymbol.Name);
            }
        }

        private static string ToPascalCase(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return name;
            }

            if (name.Length == 1)
            {
                return name.ToUpperInvariant();
            }

            return name.Substring(0, 1).ToUpperInvariant() + name.Substring(1);
        }
    }
}
