namespace KrasCore.AccumulatorGenerator
{
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Text;
    using Microsoft.CodeAnalysis;

    [Generator]
    public sealed class AccumulatorGenerator : IIncrementalGenerator
    {
        private const string ATTRIBUTE_METADATA_NAME = "KrasCore.GenerateAccumulatorForAttribute";

        private static readonly SymbolDisplayFormat FullyQualifiedFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var accumulators = context.CompilationProvider
                .Select((compilation, _) => GetAccumulators(compilation));

            context.RegisterSourceOutput(accumulators, (sourceProductionContext, accumulatorData) =>
            {
                foreach (var accumulator in accumulatorData)
                {
                    sourceProductionContext.AddSource($"{accumulator.StructName}.g.cs", GenerateSource(accumulator));
                }
            });
        }

        private static ImmutableArray<AccumulatorData> GetAccumulators(Compilation compilation)
        {
            var attributes = compilation.Assembly.GetAttributes();
            var accumulators = ImmutableArray.CreateBuilder<AccumulatorData>();
            var emittedStructs = new HashSet<string>();

            foreach (var attribute in attributes)
            {
                if (attribute.AttributeClass?.ToDisplayString() != ATTRIBUTE_METADATA_NAME)
                {
                    continue;
                }

                if (attribute.ConstructorArguments.Length != 2 ||
                    attribute.ConstructorArguments[0].Value is not ITypeSymbol typeSymbol)
                {
                    continue;
                }

                var structName = $"{typeSymbol.Name}Accumulator";
                if (!emittedStructs.Add(structName))
                {
                    continue;
                }

                accumulators.Add(new AccumulatorData(
                    typeSymbol.ToDisplayString(FullyQualifiedFormat),
                    structName,
                    GetCountExpression(attribute.ConstructorArguments[1])));
            }

            return accumulators.ToImmutable();
        }

        private static string GenerateSource(AccumulatorData accumulator)
        {
            var source = new SourceWriter();

            AppendHeader(source);
            source.Block("namespace KrasCore", namespaceWriter =>
            {
                AppendAccumulator(namespaceWriter, accumulator);
                namespaceWriter.Blank();
                AppendSumAverageExtensions(namespaceWriter, accumulator);
            });

            return source.ToString();
        }

        private static void AppendHeader(SourceWriter source)
        {
            source.Line("// <auto-generated/>");
            source.Line("#nullable enable");
            source.Blank();
        }

        private static void AppendAccumulator(SourceWriter source, AccumulatorData accumulator)
        {
            var addExpression = $"({accumulator.FullTypeName})(total + value)";
            var divideExpression = $"({accumulator.FullTypeName})(total / {accumulator.CountExpression})";

            source.Block($"public struct {accumulator.StructName} : global::KrasCore.IAccumulator<{accumulator.FullTypeName}>", structWriter =>
            {
                AppendAggressiveInlining(structWriter);
                structWriter.Block($"public {accumulator.FullTypeName} Add(in {accumulator.FullTypeName} total, in {accumulator.FullTypeName} value)", methodWriter =>
                {
                    methodWriter.Line($"return {addExpression};");
                });

                structWriter.Blank();
                AppendAggressiveInlining(structWriter);
                structWriter.Block($"public {accumulator.FullTypeName} Divide(in {accumulator.FullTypeName} total, uint count)", methodWriter =>
                {
                    methodWriter.Line($"return {divideExpression};");
                });
            });
        }

        private static void AppendSumAverageExtensions(SourceWriter source, AccumulatorData accumulator)
        {
            source.Block("public static partial class NativeLinqExtensions", classWriter =>
            {
                AppendAggressiveInlining(classWriter);
                classWriter.Line($"public static {accumulator.FullTypeName} Sum<TEnumerator>(this global::KrasCore.Query<{accumulator.FullTypeName}, TEnumerator> source)");
                classWriter.Indent();
                classWriter.Line($"where TEnumerator : unmanaged, global::System.Collections.Generic.IEnumerator<{accumulator.FullTypeName}>");
                classWriter.Unindent();
                classWriter.Block(methodWriter =>
                {
                    methodWriter.Line($"return source.Sum<{accumulator.FullTypeName}, TEnumerator, global::KrasCore.{accumulator.StructName}>();");
                });

                classWriter.Blank();
                AppendAggressiveInlining(classWriter);
                classWriter.Line($"public static {accumulator.FullTypeName} Sum<TSource, TEnumerator, TSelector>(this global::KrasCore.Query<TSource, TEnumerator> source, TSelector selector, {accumulator.FullTypeName} _ = default)");
                classWriter.Indent();
                classWriter.Line("where TSource : unmanaged");
                classWriter.Line("where TEnumerator : unmanaged, global::System.Collections.Generic.IEnumerator<TSource>");
                classWriter.Line($"where TSelector : unmanaged, global::KrasCore.ISelector<TSource, {accumulator.FullTypeName}>");
                classWriter.Unindent();
                classWriter.Block(methodWriter =>
                {
                    methodWriter.Line($"return source.Sum<TSource, {accumulator.FullTypeName}, TEnumerator, TSelector, global::KrasCore.{accumulator.StructName}>(selector);");
                });

                classWriter.Blank();
                AppendAggressiveInlining(classWriter);
                classWriter.Line($"public static {accumulator.FullTypeName} Average<TEnumerator>(this global::KrasCore.Query<{accumulator.FullTypeName}, TEnumerator> source)");
                classWriter.Indent();
                classWriter.Line($"where TEnumerator : unmanaged, global::System.Collections.Generic.IEnumerator<{accumulator.FullTypeName}>");
                classWriter.Unindent();
                classWriter.Block(methodWriter =>
                {
                    methodWriter.Line($"return source.Average<{accumulator.FullTypeName}, TEnumerator, global::KrasCore.{accumulator.StructName}>();");
                });

                classWriter.Blank();
                AppendAggressiveInlining(classWriter);
                classWriter.Line($"public static {accumulator.FullTypeName} Average<TSource, TEnumerator, TSelector>(this global::KrasCore.Query<TSource, TEnumerator> source, TSelector selector, {accumulator.FullTypeName} _ = default)");
                classWriter.Indent();
                classWriter.Line("where TSource : unmanaged");
                classWriter.Line("where TEnumerator : unmanaged, global::System.Collections.Generic.IEnumerator<TSource>");
                classWriter.Line($"where TSelector : unmanaged, global::KrasCore.ISelector<TSource, {accumulator.FullTypeName}>");
                classWriter.Unindent();
                classWriter.Block(methodWriter =>
                {
                    methodWriter.Line($"return source.Average<TSource, {accumulator.FullTypeName}, TEnumerator, TSelector, global::KrasCore.{accumulator.StructName}>(selector);");
                });
            });
        }

        private static void AppendAggressiveInlining(SourceWriter source)
        {
            source.Line("[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        }

        private static string GetCountExpression(TypedConstant divisorType)
        {
            return (int)divisorType.Value == 0 ? "(int)count" : "count";
        }
    }
}
