using KrasCore;
using Unity.Mathematics;

[assembly: GenerateAccumulatorFor(typeof(sbyte), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(byte), DivisorType.UInt)]
[assembly: GenerateAccumulatorFor(typeof(short), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(ushort), DivisorType.UInt)]
[assembly: GenerateAccumulatorFor(typeof(int), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(uint), DivisorType.UInt)]
[assembly: GenerateAccumulatorFor(typeof(long), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(ulong), DivisorType.UInt)]
[assembly: GenerateAccumulatorFor(typeof(float), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(double), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(int2), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(int3), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(int4), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(uint2), DivisorType.UInt)]
[assembly: GenerateAccumulatorFor(typeof(uint3), DivisorType.UInt)]
[assembly: GenerateAccumulatorFor(typeof(uint4), DivisorType.UInt)]
[assembly: GenerateAccumulatorFor(typeof(float2), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(float3), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(float4), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(double2), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(double3), DivisorType.Int)]
[assembly: GenerateAccumulatorFor(typeof(double4), DivisorType.Int)]
